name: Workflow Docker

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  job01:
    name: Executando jobs de teste do docker
    runs-on: ubuntu-latest
    steps:
      
    - name: Step 1
      uses: actions/checkout@v3

      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: 'mchclaro'
        password: ${{ secrets.MYSECRETDOCKER }}

      
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        tags: 'mchclaro/techchallenge:latest'
        push: true
